CREATE TABLE IF NOT EXISTS site_banner (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  image BYTEA NOT NULL,
  alt_text VARCHAR(180) NOT NULL,
  version VARCHAR(36) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_login_limits (
  bucket VARCHAR(80) PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ NOT NULL
);
